/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jesús Dorado (https://sketchfab.com/chuchodorado416)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/banana-dancing-fortnite-c1db1b10f9b14717ba731d7f49d25443
Title: Banana Dancing Fortnite
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../assets/3d/banana.glb";

const Banana = ({ currentAnimation,...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(()=>{
        Object.values(actions).forEach((action)=>action.stop());

        if(actions[currentAnimation]){
            actions[currentAnimation].play();
        }
  },[actions,currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            name="3c11148441d0473db96a8436bd7d6f7ffbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="M_MED_Bananaao" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_143"
                      geometry={nodes.Object_143.geometry}
                      material={materials.Material}
                      skeleton={nodes.Object_143.skeleton}
                    />
                    <group name="Object_142" rotation={[-Math.PI / 2, 0, 0]} />
                  </group>
                </group>
                <group name="M_MED_Bananamo" rotation={[-Math.PI / 2, 0, 0]} />
                <group
                  name="Lamp"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}
                >
                  <group name="Object_146" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_147" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[748.113, 534.367, 650.764]}
                  rotation={[Math.PI, 0.756, 2.68]}
                  scale={100}
                >
                  <group name="Object_149" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Banana;
